from __future__ import annotations

import errno
import hashlib
import html
import json
import os
import re
import tempfile
import time
from collections import defaultdict
from collections.abc import Callable
from functools import partial
from pathlib import Path
from typing import TypeVar

from .graph import AtlasGraph
from .models import Edge, Node
from .naming import note_title, safe_filename

GENERATED_MARKER = "<!-- Generated by IntentAtlas. Do not edit; run `intentatlas scan`. -->"
FILE_LOCK_RETRY_DELAYS = (0.02, 0.05, 0.1)
TRANSIENT_FILE_ERRNOS = {errno.EACCES, errno.EPERM}
TRANSIENT_WINDOWS_ERRORS = {5, 32, 33}
T = TypeVar("T")
MARKDOWN_CONTROL = re.compile(r"([\\`*_{}\[\]()!])")
USER_KINDS = {"memory", "requirement", "decision", "issue", "evidence", "review", "session"}
GENERATED_AREAS = {
    "commit": "Commits",
    "coverage": "Tests",
    "delivery-issue": "Commits/Issues",
    "pull-request": "Commits/Pull Requests",
    "symbol": "Symbols",
    "test": "Tests",
    "test-result": "Tests",
}
ALL_AREAS = (
    "Brain",
    "Requirements",
    "Decisions",
    "Issues",
    "Evidence",
    "Reviews",
    "Sessions",
    "Code",
    "Symbols",
    "Tests",
    "Commits",
    "Dashboard",
    "Templates",
    "Private",
)


class ProjectVault:
    """Owns the repository-local Obsidian vault without touching user notes on scans."""

    def __init__(self, root: Path):
        self.root = root.resolve()

    def initialize(self) -> None:
        for area in ALL_AREAS:
            (self.root / area).mkdir(parents=True, exist_ok=True)
        (self.root / ".obsidian" / "snippets").mkdir(parents=True, exist_ok=True)

        for relative, content in _OBSIDIAN_FILES.items():
            self._write_if_missing(relative, content)
        for relative, content in _STARTER_NOTES.items():
            self._write_if_missing(relative, content)

    def sync(self, graph: AtlasGraph) -> dict[str, int]:
        self.initialize()
        locations = self._note_locations(graph)

        outgoing: dict[str, list[Edge]] = defaultdict(list)
        incoming: dict[str, list[Edge]] = defaultdict(list)
        for edge in graph.edges:
            outgoing[edge.source].append(edge)
            incoming[edge.target].append(edge)

        desired: dict[Path, str] = {}
        for node in sorted(graph.nodes.values(), key=lambda item: item.id):
            if node.kind in USER_KINDS:
                continue
            relative = locations[node.id]
            target = self._safe_target(relative)
            desired[target] = self._render_node(
                node,
                graph,
                locations,
                outgoing[node.id],
                incoming[node.id],
            )

        dashboard = self._safe_target(Path("Dashboard") / "IntentAtlas.md")
        desired[dashboard] = self._render_dashboard(graph, locations)
        self._sync_generated_notes(desired)
        return {"generated_notes": len(desired) - 1, "dashboard": 1}

    def _write_if_missing(self, relative: str, content: str) -> None:
        target = self._safe_target(Path(relative))
        if target.exists():
            return
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content.rstrip() + "\n", encoding="utf-8", newline="\n")

    def _safe_target(self, relative: Path) -> Path:
        target = (self.root / relative).resolve()
        if target != self.root and self.root not in target.parents:
            raise ValueError(f"Vault target escapes root: {relative}")
        return target

    def _sync_generated_notes(self, desired: dict[Path, str]) -> None:
        for target in sorted(desired, key=lambda path: path.as_posix().casefold()):
            self._replace_generated_note(target, desired[target])
        self._prune_stale_generated_notes(set(desired))

    def _replace_generated_note(self, target: Path, content: str) -> None:
        encoded = content.encode("utf-8")
        if not target.is_symlink():
            try:
                if target.read_bytes() == encoded:
                    return
            except FileNotFoundError:
                pass
            except OSError:
                pass

        target.parent.mkdir(parents=True, exist_ok=True)
        temporary: Path | None = None
        try:
            with tempfile.NamedTemporaryFile(
                mode="w",
                encoding="utf-8",
                newline="\n",
                prefix=f".{target.name}.",
                suffix=".intentatlas.tmp",
                dir=target.parent,
                delete=False,
            ) as stream:
                temporary = Path(stream.name)
                stream.write(content)
            written = temporary
            self._retry_file_operation(lambda: os.replace(written, target))
        finally:
            if temporary is not None and temporary.exists():
                self._retry_file_operation(
                    lambda: temporary.unlink(missing_ok=True), missing_ok=True
                )

    def _prune_stale_generated_notes(self, desired: set[Path]) -> None:
        for area in sorted({*GENERATED_AREAS.values(), "Code", "Dashboard"}):
            directory = self._safe_target(Path(area))
            for path in sorted(directory.glob("*.md"), key=lambda item: item.name.casefold()):
                if path in desired or path.is_symlink():
                    continue
                prefix = self._retry_file_operation(
                    partial(path.read_text, encoding="utf-8", errors="replace"),
                    missing_ok=True,
                )
                if prefix is None:
                    continue
                if GENERATED_MARKER in prefix[:512]:
                    self._retry_file_operation(
                        partial(path.unlink), missing_ok=True
                    )

    def _retry_file_operation(
        self, operation: Callable[[], T], *, missing_ok: bool = False
    ) -> T | None:
        for delay in (*FILE_LOCK_RETRY_DELAYS, None):
            try:
                return operation()
            except FileNotFoundError:
                if missing_ok:
                    return None
                raise
            except OSError as exc:
                if delay is None or not _is_transient_file_error(exc):
                    raise
                time.sleep(delay)
        raise AssertionError("file retry schedule must not be empty")

    def _note_locations(self, graph: AtlasGraph) -> dict[str, Path]:
        locations: dict[str, Path] = {}
        used: dict[str, str] = {}
        for node in sorted(graph.nodes.values(), key=lambda item: item.id):
            if node.kind in USER_KINDS and node.path:
                locations[node.id] = Path(node.path)
                continue
            area = GENERATED_AREAS.get(node.kind, "Code")
            filename = safe_filename(note_title(node))
            key = f"{area}/{filename}".casefold()
            if key in used and used[key] != node.id:
                stem = Path(filename).stem
                digest = hashlib.sha256(node.id.encode("utf-8")).hexdigest()
                for length in range(8, len(digest) + 1, 4):
                    prefix = stem[: max(1, 170 - length)].rstrip(" .-")
                    candidate = safe_filename(f"{prefix} — {digest[:length]}")
                    candidate_key = f"{area}/{candidate}".casefold()
                    if candidate_key not in used:
                        filename = candidate
                        key = candidate_key
                        break
                else:
                    raise ValueError(
                        f"Cannot assign a unique vault note for graph node {node.id!r}"
                    )
            used[key] = node.id
            locations[node.id] = Path(area) / filename
        return locations

    def _render_node(
        self,
        node: Node,
        graph: AtlasGraph,
        locations: dict[str, Path],
        outgoing: list[Edge],
        incoming: list[Edge],
    ) -> str:
        frontmatter = [
            "---",
            f"id: {json.dumps(node.id, ensure_ascii=False)}",
            f"type: {json.dumps(node.kind)}",
            "generated: true",
        ]
        if node.path:
            frontmatter.append(f"source_path: {json.dumps(node.path, ensure_ascii=False)}")
        frontmatter.extend(
            ["---", GENERATED_MARKER, "", f"# {_markdown_text(note_title(node))}", ""]
        )

        metadata = {key: value for key, value in node.metadata.items() if key != "owner"}
        if metadata:
            frontmatter.extend(["## Metadata", ""])
            for key, value in sorted(metadata.items()):
                label = _markdown_text(key.replace("_", " ").title())
                rendered = html.escape(
                    json.dumps(value, ensure_ascii=False, sort_keys=True), quote=False
                )
                frontmatter.append(f"- **{label}:** <code>{rendered}</code>")
            frontmatter.append("")

        frontmatter.extend(
            self._render_edges("Outgoing relationships", outgoing, graph, locations, True)
        )
        frontmatter.extend(
            self._render_edges("Incoming relationships", incoming, graph, locations, False)
        )
        if not outgoing and not incoming:
            frontmatter.extend(["## Graph health", "", "- Orphaned generated node", ""])
        return "\n".join(frontmatter).rstrip() + "\n"

    @staticmethod
    def _render_edges(
        heading: str,
        edges: list[Edge],
        graph: AtlasGraph,
        locations: dict[str, Path],
        use_target: bool,
    ) -> list[str]:
        if not edges:
            return []
        lines = [f"## {heading}", ""]
        for edge in sorted(edges, key=lambda item: (item.relation, item.source, item.target)):
            other_id = edge.target if use_target else edge.source
            other = graph.nodes[other_id]
            link = locations[other_id].with_suffix("").as_posix()
            arrow = "→" if use_target else "←"
            display_relation = edge.relation if use_target else edge.inverse
            relation = html.escape(display_relation, quote=False)
            category = html.escape(edge.category, quote=False)
            evidence = _markdown_text(edge.evidence)
            lines.append(
                f"- <code>{relation}</code> {arrow} {_wikilink(link, other.label)} "
                f"_({category}; evidence: {evidence})_"
            )
        lines.append("")
        return lines

    @staticmethod
    def _render_dashboard(graph: AtlasGraph, locations: dict[str, Path]) -> str:
        summary = graph.summary()
        durable_orphans = graph.orphans(USER_KINDS)
        lines = [
            "---",
            'id: "dashboard:intentatlas"',
            'type: "dashboard"',
            "generated: true",
            "---",
            GENERATED_MARKER,
            "",
            "# IntentAtlas Dashboard",
            "",
            "> The living map from project intent to implementation evidence.",
            "",
            "## Graph summary",
            "",
        ]
        for kind, count in summary.items():
            lines.append(f"- **{_markdown_text(kind)}:** {count}")
        lines.extend(
            [
                f"- **relationships:** {len(graph.edges)}",
                f"- **orphaned durable notes:** {len(durable_orphans)}",
                "",
                "## Most connected",
                "",
            ]
        )
        connected = sorted(
            graph.nodes.values(), key=lambda node: (-graph.degree(node.id), node.label.casefold())
        )[:12]
        for node in connected:
            link = locations[node.id].with_suffix("").as_posix()
            lines.append(
                f"- {_wikilink(link, node.label)} — {graph.degree(node.id)} relationships"
            )
        lines.extend(
            [
                "",
                "## Workflow",
                "",
                "1. Capture a requirement or decision in its human-owned folder.",
                "2. Link it to implementation, tests, evidence, or another durable note.",
                "3. Run `intentatlas scan` after meaningful changes.",
                "4. Use `intentatlas impact <target>` before changing a connected node.",
                "",
            ]
        )
        return "\n".join(lines)


def _is_transient_file_error(exc: OSError) -> bool:
    return exc.errno in TRANSIENT_FILE_ERRNOS or getattr(exc, "winerror", None) in (
        TRANSIENT_WINDOWS_ERRORS
    )


def _markdown_text(value: object) -> str:
    text = str(value).replace("\r", " ").replace("\n", " ")
    escaped = html.escape(text, quote=False)
    return MARKDOWN_CONTROL.sub(r"\\\1", escaped)


def _wikilink(target: object, label: object) -> str:
    target_text = html.escape(
        str(target).replace("\\", "/").replace("\r", " ").replace("\n", " "),
        quote=False,
    )
    label_text = html.escape(
        str(label).replace("\r", " ").replace("\n", " "), quote=False
    )
    replacements = {
        "[": "&#91;",
        "]": "&#93;",
        "|": "&#124;",
        "#": "&#35;",
        "^": "&#94;",
    }
    for character, replacement in replacements.items():
        target_text = target_text.replace(character, replacement)
        label_text = label_text.replace(character, replacement)
    return f"[[{target_text}|{label_text}]]"


_OBSIDIAN_FILES: dict[str, str] = {
    ".obsidian/app.json": json.dumps(
        {
            "alwaysUpdateLinks": True,
            "showUnsupportedFiles": False,
            "userIgnoreFilters": ["Private/"],
        },
        indent=2,
    ),
    ".obsidian/appearance.json": json.dumps(
        {
            "accentColor": "#8b5cf6",
            "baseFontSize": 16,
            "enabledCssSnippets": ["intentatlas"],
        },
        indent=2,
    ),
    ".obsidian/core-plugins.json": json.dumps(
        {
            "file-explorer": True,
            "global-search": True,
            "switcher": True,
            "graph": True,
            "backlink": True,
            "canvas": True,
            "outgoing-link": True,
            "tag-pane": True,
            "properties": True,
            "page-preview": True,
            "templates": True,
            "outline": True,
            "file-recovery": True,
        },
        indent=2,
    ),
    ".obsidian/graph.json": json.dumps(
        {
            "collapse-filter": True,
            "search": "-path:Private",
            "showTags": False,
            "showAttachments": False,
            "hideUnresolved": False,
            "showOrphans": True,
            "collapse-color-groups": False,
            "colorGroups": [
                {"query": "path:Requirements", "color": {"a": 1, "rgb": 16007990}},
                {"query": "path:Decisions", "color": {"a": 1, "rgb": 16099584}},
                {"query": "path:Issues", "color": {"a": 1, "rgb": 14711848}},
                {"query": "path:Code OR path:Symbols", "color": {"a": 1, "rgb": 2323438}},
                {"query": "path:Tests", "color": {"a": 1, "rgb": 3463577}},
                {"query": "path:Evidence OR path:Reviews", "color": {"a": 1, "rgb": 9135350}},
                {"query": "path:Commits", "color": {"a": 1, "rgb": 10066329}},
            ],
            "collapse-display": True,
            "showArrow": True,
            "textFadeMultiplier": 0,
            "nodeSizeMultiplier": 1.15,
            "lineSizeMultiplier": 1.1,
            "collapse-forces": True,
            "centerStrength": 0.45,
            "repelStrength": 12,
            "linkStrength": 1,
            "linkDistance": 210,
            "scale": 0.72,
            "close": True,
        },
        indent=2,
    ),
    ".obsidian/templates.json": json.dumps({"folder": "Templates"}, indent=2),
    ".obsidian/snippets/intentatlas.css": """
.workspace-leaf-content[data-type="graph"] .view-content {
  background: radial-gradient(circle at 50% 40%, #17132c 0%, #090b14 72%);
}
.markdown-rendered blockquote {
  border-color: #8b5cf6;
  background: rgba(139, 92, 246, 0.08);
}
.metadata-container { border-radius: 12px; }
""".strip(),
}


_STARTER_NOTES: dict[str, str] = {
    "Home.md": """
---
id: home
type: map
---
# Project atlas

> Start with [[Dashboard/IntentAtlas|the living dashboard]], then define the project's durable
> outcome in `Brain/`.

## Build the intent chain

Create the first requirement, decision, issue, and evidence notes from [[Templates/Requirement]],
[[Templates/Decision]], [[Templates/Issue]], and [[Templates/Evidence]]. Link them to the code and
tests they explain, then run `intentatlas scan`.

Folders group by purpose. Links group by meaning. A durable note without a link is a bug.
""",
    "Templates/Requirement.md": """
---
id: REQ-000
type: requirement
status: proposed
---
# Requirement title

## User outcome

## Acceptance

## Links

- Decision: [[ADR-000 - Decision title]]
- Evidence: [[EVD-000 - Evidence title]]
""",
    "Templates/Decision.md": """
---
id: ADR-000
type: decision
status: proposed
---
# ADR-000 — Decision title

## Context

## Decision

## Consequences

## Links
""",
    "Templates/Issue.md": """
---
id: ISSUE-000
type: issue
status: open
---
# ISSUE-000 — Issue title

## Outcome

## Acceptance

## Typed links

- implemented-by:: [[src - package - module.py|src/package/module.py]]
""",
    "Templates/Evidence.md": """
---
id: EVD-000
type: evidence
status: pending
---
# Evidence title

## Claim

## Verification

## Links
""",
}
