from __future__ import annotations

import hashlib
import html
import json
import re
from collections import defaultdict
from pathlib import Path

from .graph import AtlasGraph
from .models import Edge, Node
from .naming import note_title, safe_filename

GENERATED_MARKER = "<!-- Generated by IntentAtlas. Do not edit; run `intentatlas scan`. -->"
MARKDOWN_CONTROL = re.compile(r"([\\`*_{}\[\]()!])")
USER_KINDS = {"memory", "requirement", "decision", "issue", "evidence", "review", "session"}
GENERATED_AREAS = {
    "commit": "Commits",
    "coverage": "Tests",
    "symbol": "Symbols",
    "test": "Tests",
    "test-result": "Tests",
}
ALL_AREAS = (
    "Brain",
    "Requirements",
    "Decisions",
    "Issues",
    "Evidence",
    "Reviews",
    "Sessions",
    "Code",
    "Symbols",
    "Tests",
    "Commits",
    "Dashboard",
    "Templates",
    "Private",
)


class ProjectVault:
    """Owns the repository-local Obsidian vault without touching user notes on scans."""

    def __init__(self, root: Path):
        self.root = root.resolve()

    def initialize(self) -> None:
        for area in ALL_AREAS:
            (self.root / area).mkdir(parents=True, exist_ok=True)
        (self.root / ".obsidian" / "snippets").mkdir(parents=True, exist_ok=True)

        for relative, content in _OBSIDIAN_FILES.items():
            self._write_if_missing(relative, content)
        for relative, content in _STARTER_NOTES.items():
            self._write_if_missing(relative, content)

    def sync(self, graph: AtlasGraph) -> dict[str, int]:
        self.initialize()
        self._purge_generated_notes()
        locations = self._note_locations(graph)

        outgoing: dict[str, list[Edge]] = defaultdict(list)
        incoming: dict[str, list[Edge]] = defaultdict(list)
        for edge in graph.edges:
            outgoing[edge.source].append(edge)
            incoming[edge.target].append(edge)

        written = 0
        for node in sorted(graph.nodes.values(), key=lambda item: item.id):
            if node.kind in USER_KINDS:
                continue
            relative = locations[node.id]
            target = self._safe_target(relative)
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(
                self._render_node(node, graph, locations, outgoing[node.id], incoming[node.id]),
                encoding="utf-8",
                newline="\n",
            )
            written += 1

        dashboard = self._safe_target(Path("Dashboard") / "IntentAtlas.md")
        dashboard.write_text(
            self._render_dashboard(graph, locations), encoding="utf-8", newline="\n"
        )
        return {"generated_notes": written, "dashboard": 1}

    def _write_if_missing(self, relative: str, content: str) -> None:
        target = self._safe_target(Path(relative))
        if target.exists():
            return
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content.rstrip() + "\n", encoding="utf-8", newline="\n")

    def _safe_target(self, relative: Path) -> Path:
        target = (self.root / relative).resolve()
        if target != self.root and self.root not in target.parents:
            raise ValueError(f"Vault target escapes root: {relative}")
        return target

    def _purge_generated_notes(self) -> None:
        for area in {*GENERATED_AREAS.values(), "Code", "Dashboard"}:
            directory = self._safe_target(Path(area))
            for path in directory.glob("*.md"):
                if path.is_symlink():
                    continue
                try:
                    prefix = path.read_text(encoding="utf-8", errors="replace")[:512]
                except OSError:
                    continue
                if GENERATED_MARKER in prefix:
                    path.unlink()

    def _note_locations(self, graph: AtlasGraph) -> dict[str, Path]:
        locations: dict[str, Path] = {}
        used: dict[str, str] = {}
        for node in sorted(graph.nodes.values(), key=lambda item: item.id):
            if node.kind in USER_KINDS and node.path:
                locations[node.id] = Path(node.path)
                continue
            area = GENERATED_AREAS.get(node.kind, "Code")
            filename = safe_filename(note_title(node))
            key = f"{area}/{filename}".casefold()
            if key in used and used[key] != node.id:
                stem = Path(filename).stem
                digest = hashlib.sha256(node.id.encode("utf-8")).hexdigest()
                for length in range(8, len(digest) + 1, 4):
                    prefix = stem[: max(1, 170 - length)].rstrip(" .-")
                    candidate = safe_filename(f"{prefix} — {digest[:length]}")
                    candidate_key = f"{area}/{candidate}".casefold()
                    if candidate_key not in used:
                        filename = candidate
                        key = candidate_key
                        break
                else:
                    raise ValueError(
                        f"Cannot assign a unique vault note for graph node {node.id!r}"
                    )
            used[key] = node.id
            locations[node.id] = Path(area) / filename
        return locations

    def _render_node(
        self,
        node: Node,
        graph: AtlasGraph,
        locations: dict[str, Path],
        outgoing: list[Edge],
        incoming: list[Edge],
    ) -> str:
        frontmatter = [
            "---",
            f"id: {json.dumps(node.id, ensure_ascii=False)}",
            f"type: {json.dumps(node.kind)}",
            "generated: true",
        ]
        if node.path:
            frontmatter.append(f"source_path: {json.dumps(node.path, ensure_ascii=False)}")
        frontmatter.extend(
            ["---", GENERATED_MARKER, "", f"# {_markdown_text(note_title(node))}", ""]
        )

        metadata = {key: value for key, value in node.metadata.items() if key != "owner"}
        if metadata:
            frontmatter.extend(["## Metadata", ""])
            for key, value in sorted(metadata.items()):
                label = _markdown_text(key.replace("_", " ").title())
                rendered = html.escape(
                    json.dumps(value, ensure_ascii=False, sort_keys=True), quote=False
                )
                frontmatter.append(f"- **{label}:** <code>{rendered}</code>")
            frontmatter.append("")

        frontmatter.extend(
            self._render_edges("Outgoing relationships", outgoing, graph, locations, True)
        )
        frontmatter.extend(
            self._render_edges("Incoming relationships", incoming, graph, locations, False)
        )
        if not outgoing and not incoming:
            frontmatter.extend(["## Graph health", "", "- Orphaned generated node", ""])
        return "\n".join(frontmatter).rstrip() + "\n"

    @staticmethod
    def _render_edges(
        heading: str,
        edges: list[Edge],
        graph: AtlasGraph,
        locations: dict[str, Path],
        use_target: bool,
    ) -> list[str]:
        if not edges:
            return []
        lines = [f"## {heading}", ""]
        for edge in sorted(edges, key=lambda item: (item.relation, item.source, item.target)):
            other_id = edge.target if use_target else edge.source
            other = graph.nodes[other_id]
            link = locations[other_id].with_suffix("").as_posix()
            arrow = "→" if use_target else "←"
            display_relation = edge.relation if use_target else edge.inverse
            relation = html.escape(display_relation, quote=False)
            category = html.escape(edge.category, quote=False)
            evidence = _markdown_text(edge.evidence)
            lines.append(
                f"- <code>{relation}</code> {arrow} {_wikilink(link, other.label)} "
                f"_({category}; evidence: {evidence})_"
            )
        lines.append("")
        return lines

    @staticmethod
    def _render_dashboard(graph: AtlasGraph, locations: dict[str, Path]) -> str:
        summary = graph.summary()
        durable_orphans = graph.orphans(USER_KINDS)
        lines = [
            "---",
            'id: "dashboard:intentatlas"',
            'type: "dashboard"',
            "generated: true",
            "---",
            GENERATED_MARKER,
            "",
            "# IntentAtlas Dashboard",
            "",
            "> The living map from project intent to implementation evidence.",
            "",
            "- North star: [[Brain/North Star]]",
            "- Active requirement: [[Requirements/REQ-001 - Explain change impact]]",
            "- Architecture decision: [[Decisions/ADR-001 - Vault-first intent graph]]",
            "- Latest evidence: [[Evidence/EVD-001 - Initial scanner acceptance]]",
            "- Project review: [[Reviews/Initial Project Review]]",
            "",
            "## Graph summary",
            "",
        ]
        for kind, count in summary.items():
            lines.append(f"- **{_markdown_text(kind)}:** {count}")
        lines.extend(
            [
                f"- **relationships:** {len(graph.edges)}",
                f"- **orphaned durable notes:** {len(durable_orphans)}",
                "",
                "## Most connected",
                "",
            ]
        )
        connected = sorted(
            graph.nodes.values(), key=lambda node: (-graph.degree(node.id), node.label.casefold())
        )[:12]
        for node in connected:
            link = locations[node.id].with_suffix("").as_posix()
            lines.append(
                f"- {_wikilink(link, node.label)} — {graph.degree(node.id)} relationships"
            )
        lines.extend(
            [
                "",
                "## Workflow",
                "",
                "1. Capture a requirement or decision in its human-owned folder.",
                "2. Link it to implementation, tests, evidence, or another durable note.",
                "3. Run `intentatlas scan` after meaningful changes.",
                "4. Use `intentatlas impact <target>` before changing a connected node.",
                "",
            ]
        )
        return "\n".join(lines)


def _markdown_text(value: object) -> str:
    text = str(value).replace("\r", " ").replace("\n", " ")
    escaped = html.escape(text, quote=False)
    return MARKDOWN_CONTROL.sub(r"\\\1", escaped)


def _wikilink(target: object, label: object) -> str:
    target_text = html.escape(
        str(target).replace("\\", "/").replace("\r", " ").replace("\n", " "),
        quote=False,
    )
    label_text = html.escape(
        str(label).replace("\r", " ").replace("\n", " "), quote=False
    )
    replacements = {
        "[": "&#91;",
        "]": "&#93;",
        "|": "&#124;",
        "#": "&#35;",
        "^": "&#94;",
    }
    for character, replacement in replacements.items():
        target_text = target_text.replace(character, replacement)
        label_text = label_text.replace(character, replacement)
    return f"[[{target_text}|{label_text}]]"


_OBSIDIAN_FILES: dict[str, str] = {
    ".obsidian/app.json": json.dumps(
        {
            "alwaysUpdateLinks": True,
            "showUnsupportedFiles": False,
            "userIgnoreFilters": ["Private/"],
        },
        indent=2,
    ),
    ".obsidian/appearance.json": json.dumps(
        {
            "accentColor": "#8b5cf6",
            "baseFontSize": 16,
            "enabledCssSnippets": ["intentatlas"],
        },
        indent=2,
    ),
    ".obsidian/core-plugins.json": json.dumps(
        {
            "file-explorer": True,
            "global-search": True,
            "switcher": True,
            "graph": True,
            "backlink": True,
            "canvas": True,
            "outgoing-link": True,
            "tag-pane": True,
            "properties": True,
            "page-preview": True,
            "templates": True,
            "outline": True,
            "file-recovery": True,
        },
        indent=2,
    ),
    ".obsidian/graph.json": json.dumps(
        {
            "collapse-filter": True,
            "search": "-path:Private",
            "showTags": False,
            "showAttachments": False,
            "hideUnresolved": False,
            "showOrphans": True,
            "collapse-color-groups": False,
            "colorGroups": [
                {"query": "path:Requirements", "color": {"a": 1, "rgb": 16007990}},
                {"query": "path:Decisions", "color": {"a": 1, "rgb": 16099584}},
                {"query": "path:Issues", "color": {"a": 1, "rgb": 14711848}},
                {"query": "path:Code OR path:Symbols", "color": {"a": 1, "rgb": 2323438}},
                {"query": "path:Tests", "color": {"a": 1, "rgb": 3463577}},
                {"query": "path:Evidence OR path:Reviews", "color": {"a": 1, "rgb": 9135350}},
                {"query": "path:Commits", "color": {"a": 1, "rgb": 10066329}},
            ],
            "collapse-display": True,
            "showArrow": True,
            "textFadeMultiplier": 0,
            "nodeSizeMultiplier": 1.15,
            "lineSizeMultiplier": 1.1,
            "collapse-forces": True,
            "centerStrength": 0.45,
            "repelStrength": 12,
            "linkStrength": 1,
            "linkDistance": 210,
            "scale": 0.72,
            "close": True,
        },
        indent=2,
    ),
    ".obsidian/templates.json": json.dumps({"folder": "Templates"}, indent=2),
    ".obsidian/snippets/intentatlas.css": """
.workspace-leaf-content[data-type="graph"] .view-content {
  background: radial-gradient(circle at 50% 40%, #17132c 0%, #090b14 72%);
}
.markdown-rendered blockquote {
  border-color: #8b5cf6;
  background: rgba(139, 92, 246, 0.08);
}
.metadata-container { border-radius: 12px; }
""".strip(),
}


_STARTER_NOTES: dict[str, str] = {
    "Home.md": """
---
id: home
type: map
---
# IntentAtlas

> Start with [[Dashboard/IntentAtlas|the living dashboard]] and [[Brain/North Star]].

## Intent chain

[[Requirements/REQ-001 - Explain change impact]] →
[[Decisions/ADR-001 - Vault-first intent graph]] →
[[Evidence/EVD-001 - Initial scanner acceptance]] →
[[Reviews/Initial Project Review]]

Folders group by purpose. Links group by meaning. A durable note without a link is a bug.
""",
    "Brain/North Star.md": """
---
id: north-star
type: memory
status: active
---
# North Star

Make the reason behind software changes as inspectable as the code itself.

The first promise is [[Requirements/REQ-001 - Explain change impact]]. Decisions must carry
forward into code, tests, evidence, reviews, and commits without locking the user into a
hosted service.
""",
    "Requirements/REQ-001 - Explain change impact.md": """
---
id: REQ-001
type: requirement
status: accepted
---
# Explain change impact

Before changing a project artifact, a developer can see its upstream intent and downstream
implementation or verification relationships.

## Acceptance

- A local scan creates a deterministic relationship graph.
- The graph is explorable in Obsidian and a standalone local viewer.
- Impact can be queried without sending source code to an external service.

Implemented through [[Decisions/ADR-001 - Vault-first intent graph]] and verified by
[[Evidence/EVD-001 - Initial scanner acceptance]].
""",
    "Decisions/ADR-001 - Vault-first intent graph.md": """
---
id: ADR-001
type: decision
status: accepted
---
# ADR-001 — Vault-first intent graph

## Decision

Human and agent knowledge remains portable Markdown with wikilinks. Rebuildable scanner
output connects that knowledge to code structure and Git history.

## Why

The vault stays useful without IntentAtlas, Obsidian, an account, or an API key. This supports
[[Requirements/REQ-001 - Explain change impact]] while keeping meaning under user control.

## Implementation

The language-neutral graph lives in [[src - intentatlas - graph.py]]. Generated notes are
separate from user-owned notes so scans cannot overwrite decisions.
""",
    "Evidence/EVD-001 - Initial scanner acceptance.md": """
---
id: EVD-001
type: evidence
status: pending
---
# Initial scanner acceptance

Evidence for [[Requirements/REQ-001 - Explain change impact]]:

- Scanner and graph tests: [[tests - test_scanner.py]] and [[tests - test_graph.py]]
- Vault ownership tests: [[tests - test_vault.py]]
- CLI acceptance tests: [[tests - test_cli.py]]

Update this note with verified command output before the first public release.
""",
    "Reviews/Initial Project Review.md": """
---
id: REVIEW-001
type: review
status: open
---
# Initial Project Review

Review [[Evidence/EVD-001 - Initial scanner acceptance]] against
[[Requirements/REQ-001 - Explain change impact]] before publishing.

## Checklist

- [ ] A fresh install works without network access after dependencies are installed.
- [ ] Generated notes contain no raw source or secrets.
- [ ] Obsidian Graph View clearly separates intent, implementation, tests, and evidence.
- [ ] The local viewer works on a representative repository.
""",
    "Sessions/2026-07-30 - Project bootstrap.md": """
---
id: SESSION-2026-07-30-BOOTSTRAP
type: session
status: complete
---
# 2026-07-30 — Project bootstrap

IntentAtlas started from [[Brain/North Star]] with a clean repository and a vault-first
architecture inspired by obsidian-mind. The first delivery target is
[[Requirements/REQ-001 - Explain change impact]].
""",
    "Templates/Requirement.md": """
---
id: REQ-000
type: requirement
status: proposed
---
# Requirement title

## User outcome

## Acceptance

## Links

- Decision: [[ADR-000 - Decision title]]
- Evidence: [[EVD-000 - Evidence title]]
""",
    "Templates/Decision.md": """
---
id: ADR-000
type: decision
status: proposed
---
# ADR-000 — Decision title

## Context

## Decision

## Consequences

## Links
""",
    "Templates/Issue.md": """
---
id: ISSUE-000
type: issue
status: open
---
# ISSUE-000 — Issue title

## Outcome

## Acceptance

## Typed links

- implemented-by:: [[src - package - module.py|src/package/module.py]]
""",
    "Templates/Evidence.md": """
---
id: EVD-000
type: evidence
status: pending
---
# Evidence title

## Claim

## Verification

## Links
""",
}
